{% set name = "openldap" %}
{% set version = "2.6.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://www.openldap.org/software/download/OpenLDAP/{{ name }}-release/{{ name }}-{{ version }}.tgz
  sha256: 1716ad779e85d743694c3e3b05277fb71b6a5eadca43c7a958aa62683b22208e

build:
  number: 0
  skip: True  # [not unix]
  run_exports:
    - {{ pin_subpackage('openldap', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - groff
  host:
    - libevent {{ libevent }}
    - libsodium {{ libsodium }}
    - openssl {{ openssl }}
    - cyrus-sasl {{ cyrus_sasl }}
  run:
    - openssl >=3
    - cyrus-sasl >=2.1.27

about:
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  description: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  doc_url: https://www.openldap.org/doc
  dev_url: https://www.openldap.org/software/repo.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
    - chenghlee
