{% set name = "openldap" %}
{% set version = "2.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://www.openldap.org/software/download/OpenLDAP/openldap-release/{{ name }}-{{ version }}.tgz
  sha256: 9d576ea6962d7db8a2e2808574e8c257c15aef55f403a1fb5a0faf35de70e6f3

build:
  number: 0
  skip: True  # [not unix]
  run_exports:
    - {{ pin_subpackage('openldap', max_pin='x.x') }}
  ignore_run_exports:
    # package on defaults contains only static libs
    - cyrus-sasl    # [ppc64le]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - groff
  host:
    - openssl
    - cyrus-sasl
  run:
    - openssl
    - cyrus-sasl

test:
  commands:
    - test $PREFIX/include/ldap.h   # [unix]

about:
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  doc_url: https://www.openldap.org/doc/
  dev_url: https://www.openldap.org/software/repo.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
    - chenghlee
