{% set name = "openldap" %}
{% set version = "2.6.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://www.openldap.org/software/download/OpenLDAP/openldap-release/{{ name }}-{{ version }}.tgz
  sha256: d51704e50178430c06cf3d8aa174da66badf559747a47d920bb54b2d4aa40991

build:
  number: 1
  skip: True  # [not unix]
  skip: True  # [linux and s390x]
  run_exports:
    - {{ pin_subpackage('openldap', max_pin='x.x') }}
  ignore_run_exports:
    # package on defaults contains only static libs
    - cyrus-sasl    # [ppc64le]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - groff
  host:
    - openssl {{ openssl }}
    - cyrus-sasl 2.1.28
  run:
    - openssl 3.*
    - cyrus-sasl

test:
  commands:
    - test $PREFIX/include/ldap.h   # [unix]

about:
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  description: >
    OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
  doc_url: https://www.openldap.org/doc/
  dev_url: https://www.openldap.org/software/repo.html

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
    - chenghlee
